on:
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish PowerShell Module
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}